language: node_js
env:
  - CXX=g++-4.8 NODE_ENV=test
before_install:
  - cp config.json.example config.json
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "5.11"
